services:
  userbot:
    build: .
    container_name: toujibot_user
    restart: unless-stopped
    volumes:
      - ./:/app
    command: sh scripts/run_userbot.sh
    environment:
      - TZ=Asia/Shanghai
    env_file:
      - .env
    stdin_open: true
    tty: true

  relaybot:
    build: .
    container_name: toujibot_relay
    restart: unless-stopped
    volumes:
      - ./:/app
    command: sh scripts/run_relaybot.sh
    environment:
      - TZ=Asia/Shanghai
    env_file:
      - .env
